### ISSUE TITLE
libCore.so not loading for configuration v0.3.0-rhel7-root6.24.06.config

### ISSUE THREAD

**Issue by genevb** [star-bnl/star-sw#744]
I haven't tried this in many months. This was working before, but something has broken...

    [rcas6003] ~/> starver SL24x config/v0.3.0-rhel7-root6.24.06
    [rcas6003] ~/> which root4star
    /afs/rhic.bnl.gov/star/packages/SL24x/.sl73_gcc485/bin/root4star
    [rcas6003] ~/> root4star -b -l
    root4star: error while loading shared libraries: libCore.so.6.24: cannot open shared object file: No such file or directory

The same error arises when using NFS4 instead of AFS.

-Gene

**Comment by klendathu2k** [comment]
The issue is that we have a mixed environment.  ROOT5 and ROOT6 libraries are both available in the search path, and we're trying to load the wrong one.

I have a hack which works, but we need a _solution_ to this problem.

```
echo $LD_LIBRARY_PATH
...
/afs/rhic.bnl.gov/star/ROOT/5.34.38/.sl73_x8664_gcc485/rootdeb/lib
...
```

**Comment by plexoos** [comment]
According to the CVS logs, it looks like there was a significant update to `group_env.csh` (`/afs/rhic.bnl.gov/star/packages/repository/group/group_env.csh,v`) on 2025/02/11 with a message "Missing logic for years + execute starver for consistency" by Jerome.
It seems like something is unsetting the `$cf` variable, which is set from the second parameter in this command: starver SL24x config/v0.3.0-rhel7-root6.24.06, and as a result, the Spack environment isn’t being set up.

**Comment by plexoos** [comment]
Here are the lines in `group_env.csh` that presumably ignore the Spack configs:

```
1123                                                                                                                          
1124                                                                                                                          
1125 # After the introduction of SPACK, we created                                                                            
1126 # an inconsistency that could bre paired this way                                                                        
1127 if ( $?STAR_LEVEL ) then                                                                                                 
1128     setenv EXEFLOGIN 1                                                                                                   
1129     starver $STAR_LEVEL                                                                                                  
1130     unsetenv EXEFLOGIN                                                                                                   
1131 endif                                                                                                                    
1132                                                                                                                          
1133               
```

**Comment by plexoos** [comment]
So, if I understand correctly, the `starver` script invokes `group_env.csh`, which in turn executes `starver` again without passing the “config” parameter.

**Comment by genevb** [comment]
Jerome has [implemented](https://www.star.bnl.gov/cgi-bin/protected/viewvc.cgi/cvsroot/group/group_env.csh?r1=1.269&r2=1.270&sortby=date) the proposed fix from @plexoos . Unfortunately, the issue remains. At this time, I only have 64-bit unoptimized SL24x built, in both AFS and NFSv4, so `setup 64b` is required before the `starver ...` in my original how-to-reproduce.

**Comment by plexoos** [comment]
Thanks for checking, Gene. I'll take another look. I assume `setup 64b` has always been required before `starver ...` to set `$USE_64BITS`

**Comment by klendathu2k** [comment]
TL;DR

group_env.csh
```
1129     if ( $?STAR_CF ) then
1130         starver $STAR_LEVEL $STAR_CF
1131     else
1132         starver $STAR_LEVEL
1133     endif
```

On lines 1129 and 1130, `STAR_CF` should be `STAR_CONFIG`.

---------

I have done a bit of poking around and here is what I see.  After doing
```
setup 64b
starver SL24x config/v0.3.0-rhel7-root6.24.06
```

We have two versions of ROOT in the path, both of which are root 5.34.
```
$ echo $LD_LIBRARY_PATH | sed 's/:/\n/g' | grep -i root
/cvmfs/star.sdcc.bnl.gov/star-spack/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/root-5.34.38-eyawaunrtayjlt3aqon5claakm3c7xl7/lib
/afs/rhic.bnl.gov/star/ROOT/5.34.38/.sl73_x8664_gcc485/rootdeb/lib
```

If I run with debugging output enabled:
```
setenv DECHO 1
setup 64b
starver SL24x config/v0.3.0-rhel7-root6.24.06
```

I see that the `$GROUP_DIR/.starver` script _should_ be loading the correct spack configuration...
```
$ starver SL24x config/v0.3.0-rhel7-root6.24.06
-tcsh :: receiving argument [SL24x config/v0.3.0-rhel7-root6.24.06]
-tcsh :: STAR_LEVEL = SL24x cf=config/v0.3.0-rhel7-root6.24.06
... more debug output 
```

But by the time the configuration is setup, the configuration is lost.
```
... more debug output
group_env :: done
-tcsh :: Verifying config
-tcsh :: Config is now default
starver :: Loading configuration  (/afs/rhic.bnl.gov/star/packages/SL24x/mgr/default.config)
```

Digging into the scripts themselves...  

`.starver` calls `group_env.csh` which, in turn, calls `.starver`.

The first call to `.starver` sets the `STAR_CONFIG` variable, with the name of the configuration file.  The `group_env.csh` later calls starver, but uses an undefined `STAR_CF` environment variable.

**Comment by jlauret** [comment]
STAR_CF is not the same as STAR_CONFIG simply because the latest may not be defined.
Also the sequence
```
setup 64b
starver SL24x config/v0.3.0-rhel7-root6.24.06
root4star -b -l
```

works fine for me. Checking more.

Addendum - I have a different call stack (in min ethe config is consistent). Which GROUP_DIR is being used in your case? 

```
group_env :: Paths cleanup ...
-tcsh :: receiving argument [SL24x config/v0.3.0-rhel7-root6.24.06]
-tcsh :: STAR_LEVEL = SL24x cf=config/v0.3.0-rhel7-root6.24.06
-tcsh :: Verifying config
-tcsh :: Config is now config/v0.3.0-rhel7-root6.24.06
starver :: Loading configuration config/v0.3.0-rhel7-root6.24.06 (/afs/rhic.bnl.gov/star/packages/SL24x/mgr/config/v0.3.0-rhel7-root6.24.06.config)
group_env :: done
-tcsh :: Verifying config
-tcsh :: Config is now config/v0.3.0-rhel7-root6.24.06
starver :: Loading configuration config/v0.3.0-rhel7-root6.24.06 (/afs/rhic.bnl.gov/star/packages/SL24x/mgr/config/v0.3.0-rhel7-root6.24.06.config)
```

**Comment by klendathu2k** [comment]
Using `/afs/rhic/rhstar/group/`

**Comment by genevb** [comment]
> Which GROUP_DIR is being used in your case?

@jlauret , here's from a fresh SL7 login for the starlib account:

```
[rcas6003] ~/> whoami
starlib
[rcas6003] ~/> echo $GROUP_DIR
/star/u/jeromel/work/STAR/group
[rcas6003] ~/> setup 64b
[rcas6003] ~/> starver SL24x config/v0.3.0-rhel7-root6.24.06
[rcas6003] ~/> echo $GROUP_DIR
/star/u/jeromel/work/STAR/group
[rcas6003] ~/> root4star -b -l
root4star: error while loading shared libraries: libCore.so.6.24: cannot open shared object file: No such file or directory
[rcas6003] ~/> which root4star
/star/nfs4/AFS/star/packages/SL24x/.sl73_x8664_gcc485/bin/root4star
```

**Comment by genevb** [comment]
@klendathu2k , @plexoos :
Jerome helped with resolving the libCore.so error when using NFSv4, but executing `root4star` shows some different cling-related errors. So I tried rebuilding the NFSv4 SL24x today, but after completing, it shows the same cling-related errors. Any suggestions?
```
[rcas6003] ~/> setup 64b
[rcas6003] ~/> starver SL24x config/v0.3.0-rhel7-root6.24.06
[rcas6003] ~/> which root4star
/star/nfs4/AFS/star/packages/SL24x/.sl73_x8664_gcc485/bin/root4star
[rcas6003] ~/> ls -l `which root4star`
lrwxrwxrwx 1 starlib rhstar 48 Jun 10 12:06 /star/nfs4/AFS/star/packages/SL24x/.sl73_x8664_gcc485/bin/root4star -> ../../.sl73_x8664_gcc485/obj/asps/rexe/root4star
[rcas6003] ~/> root4star -b -l
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for StarMC.h
   requested to autoload type StarMC
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for TGiant3.h
   requested to autoload type Gcflag_t
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for TGiant3.h
   requested to autoload type TGiant3
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for StThreeVector.hh
   requested to autoload type StThreeVector
...
(zillions of such errors omitted)
...
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for TRungeKutta.h
   requested to autoload type TRungeKutta
 *** Start at Date : Tue Jun 10 17:19:50 2025
root [0] 
```

NB: Jerome says it is best to use his $GROUP_DIR for NFSv4 for now:
`/star/u/jeromel/work/STAR/group`

p.s. I'm also rebuilding the AFS SL24x and will report back on the status of running root4star there when building completes, maybe later tonight.

**Comment by plexoos** [comment]
Could you clarify what it means to use `$GROUP_DIR=/star/u/jeromel/work/STAR/group`?

In my `.cshrc`, I only have this line:  
```csh
source /afs/rhic.bnl.gov/rhstar/group/star_cshrc.csh
```

Am I supposed to replace it with:  
```csh
source /star/u/jeromel/work/STAR/group/star_cshrc.csh
```
? I don't think I’ve ever explicitly set `GROUP_DIR` anywhere.

In any case, sourcing that last script doesn’t seem to set the correct ROOT6 executable.

Here’s what I see:

```sh
[cvmfswrite01] ~/> setup 64b
[cvmfswrite01] ~/> starver SL24x config/v0.3.0-rhel7-root6.24.06
[cvmfswrite01] ~/> which root
/cvmfs/star.sdcc.bnl.gov/star-spack/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/root-5.34.38-eyawaunrtayjlt3aqon5claakm3c7xl7/bin/root
```

So it’s still picking up ROOT5.

**Comment by genevb** [comment]
Hi, @plexoos 

I'm not sure where all the $GROUP_DIR environment variable is used, but my impression is that to do it right, you need to source both the login and cshrc from $GROUP_DIR after assigning it.

The starlib account is using Jerome's $GROUP_DIR, and it does show ROOT6:
```
[rcas6003] ~/> setup 64b
[rcas6003] ~/> starver SL24x config/v0.3.0-rhel7-root6.24.06
[rcas6003] ~/> which root
/cvmfs/star.sdcc.bnl.gov/star-spack/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/root-6.24.06-ojgeqx4c6cazamrg2mltgfm3wpivwzyf/bin/root
```
And `root4star -b` (without -l) shows the following (along with the numerous cling-related errors I noted earlier today):
```
   ------------------------------------------------------------------
  | Welcome to ROOT 6.24/06                        https://root.cern |
  | (c) 1995-2021, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Sep 02 2021, 14:20:23                 |
  | From tags/v6-24-06@v6-24-06                                      |
  | With g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)                 |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q'       |
   ------------------------------------------------------------------
```

**Comment by klendathu2k** [comment]
I suspect `$STAR/asps/rexe/rexeLinkDef.h` needs to have __CLING__ added to the #ifdef guard.  


-------

Those errors suggest that the ROOT_INCLUDE_PATH does not contain the path to the header files...  After setting up for nfs4, 64b, SL24x... I see the correct config has been set...
```
$ setup nfs4
$ setup 64b
$ setenv GROUP_DIR /star/u/jeromel/work/STAR/group
$ starver SL24x config/v0.3.0-rhel7-root6.24.06
...
starver :: Loading configuration config/v0.3.0-rhel7-root6.24.06 (/star/nfs4/AFS/star/packages/SL24x/mgr/config/v0.3.0-rhel7-root6.24.06.config)
```

And ... I don't see 'zillions' of errors.  Only 3:
```
$ root4star
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for StarMC.h
   requested to autoload type StarMC
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for TGiant3.h
   requested to autoload type Gcflag_t
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for TGiant3.h
   requested to autoload type TGiant3
```

But two interesting things to note... 
1) The include path contains $STAR/.$STAR_HOST_SYS/include ...
```
root [0] gSystem->GetIncludePath()
```

2) root knows about these classes / structs... (note the `tab` in the interactive root session...)
```
root [0] Gcflag_t f;
root [1] f.\t
Gcflag_t
idebug
idemax
idemin
idevt
idrun
ieorun
ieotri
ievent
ifinit
iswit
itest
nevent
nrndm
operator=
~Gcflag_t
```


> [@klendathu2k](https://github.com/klendathu2k) , [@plexoos](https://github.com/plexoos) : Jerome helped with resolving the libCore.so error when using NFSv4, but executing `root4star` shows some different cling-related errors. So I tried rebuilding the NFSv4 SL24x today, but after completing, it shows the same cling-related errors. Any suggestions?
> 
> ```
> [rcas6003] ~/> setup 64b
> [rcas6003] ~/> starver SL24x config/v0.3.0-rhel7-root6.24.06
> [rcas6003] ~/> which root4star
> /star/nfs4/AFS/star/packages/SL24x/.sl73_x8664_gcc485/bin/root4star
> [rcas6003] ~/> ls -l `which root4star`
> lrwxrwxrwx 1 starlib rhstar 48 Jun 10 12:06 /star/nfs4/AFS/star/packages/SL24x/.sl73_x8664_gcc485/bin/root4star -> ../../.sl73_x8664_gcc485/obj/asps/rexe/root4star
> [rcas6003] ~/> root4star -b -l
> Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
>    Missing FileEntry for StarMC.h
>    requested to autoload type StarMC
> Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
>    Missing FileEntry for TGiant3.h
>    requested to autoload type Gcflag_t
> Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
>    Missing FileEntry for TGiant3.h
>    requested to autoload type TGiant3
> Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
>    Missing FileEntry for StThreeVector.hh
>    requested to autoload type StThreeVector
> ...
> (zillions of such errors omitted)
> ...
> Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
>    Missing FileEntry for TRungeKutta.h
>    requested to autoload type TRungeKutta
>  *** Start at Date : Tue Jun 10 17:19:50 2025
> root [0] 
> ```
> 
> NB: Jerome says it is best to use his $GROUP_DIR for NFSv4 for now: `/star/u/jeromel/work/STAR/group`
> 
> p.s. I'm also rebuilding the AFS SL24x and will report back on the status of running root4star there when building completes, maybe later tonight.

**Comment by genevb** [comment]
FYI, the AFS build of SL24x seems happy when using Jerome's $GROUP_DIR:
```
[rcas6003] ~/> setup afs
[rcas6003] ~/> setup 64b
[rcas6003] ~/> starver SL24x config/v0.3.0-rhel7-root6.24.06
[rcas6003] ~/> which root4star
/afs/rhic.bnl.gov/star/packages/SL24x/.sl73_x8664_gcc485/bin/root4star
[rcas6003] ~/> which root
/cvmfs/star.sdcc.bnl.gov/star-spack/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/root-6.24.06-ojgeqx4c6cazamrg2mltgfm3wpivwzyf/bin/root
[rcas6003] ~/> root4star -b
   ------------------------------------------------------------------
  | Welcome to ROOT 6.24/06                        https://root.cern |
  | (c) 1995-2021, The ROOT Team; conception: R. Brun, F. Rademakers |
  | Built for linuxx8664gcc on Sep 02 2021, 14:20:23                 |
  | From tags/v6-24-06@v6-24-06                                      |
  | With g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)                 |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q'       |
   ------------------------------------------------------------------

 *** Start at Date : Wed Jun 11 09:19:07 2025
root [0] 
```

**Comment by plexoos** [comment]
```
[rcas6003] ~/> setup afs
```

There’s always something new :)

Anyway, these commands seem to be working for me now, and I can see the expected root in my PATH.

**Comment by genevb** [comment]
> asps/rexe/rexeLinkDef.h

Two notes...

1. I tried replacing `#ifdef __CINT__` with `#if defined(__CINT__) || defined(__CLING__)` in the file @klendathu2k (Jason) suggested, and rebuild `asps`, but that had no affect on the run-time errors I see with root4star.
2. It occurred to me to try `root`, which itself shouldn't be specific to my SL24x build, but that also shows cling errors:
```
[rcas6003] ~/> which root
/cvmfs/star.sdcc.bnl.gov/star-spack/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/root-6.24.06-ojgeqx4c6cazamrg2mltgfm3wpivwzyf/bin/root
[rcas6003] ~/> root -l -b -q |& grep -c Error
75
[rcas6003] ~/> which root4star
/star/nfs4/AFS/star/packages/SL24x/.sl73_x8664_gcc485/bin/root4star
[rcas6003] ~/> root4star -l -b -q | & grep -c Error
78
```
The 3 different errors appear to be the same 3 Jason reported seeing with root4star, so I'm just going to guess he sees no cling errors from `root`.

**Comment by jlauret** [comment]
I have resolved this issue. It may have been a compilation issue as well but the root cause is that `ROOT_INCLUDE_PATH` needed to include `$STAR/.$STAR_HOST_SYS/include` . This is fixed in my local directory ( that `/star/u/jeromel/work/STAR/group` as `GROUP_DIR` ) where if `ROOT_INCLUDE_PATH` is defined, the proper addition is added. If all seems fixed, I could commit. This did not need to be set before (`rootlogon.C` added it `  gSystem->AddIncludePath(" -I./.$STAR_HOST_SYS/include -I./StRoot -I$STAR/.$STAR_HOST_SYS/include -I$STAR/StRoot -I/usr/include/mysql");` ).

I expect more issues moving forward 
- a collapse of xrootd access due to alos missing directive in `rootlogon.C` .
- break of the mechanism by which a user's custom logon script would be loaded
- etc ...

**Comment by genevb** [comment]
Yesterday's change by Jerome resolved the cling-related errors for me (merci). It would be good if @klendathu2k also confirms that SL24x appears to be working with Jerome's $GROUP_DIR so that he can commit and we can update the standard $GROUP_DIR.

**Comment by klendathu2k** [comment]
Those changes resolve the libCore.so issue.   (Other issues persist, but are not due to the group environment).

**Comment by plexoos** [comment]
Here is the `rootlogon.C` we use: https://github.com/star-bnl/star-sw/blob/main/StRoot/macros/rootlogon.C

**It includes all the paths listed by Jerome above.**

This is exactly the `rootlogon.C` referenced by the `system.rootrc` file when ROOT is installed. Here’s the relevant line:

```
Rint.Logon:                 $(STAR)/StRoot/macros/rootlogon.C
```

This can be confirmed for ROOT6:

```
tail /cvmfs/star.sdcc.bnl.gov/star-spack/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/root-6.24.06-ojgeqx4c6cazamrg2mltgfm3wpivwzyf/etc/system.rootrc
```

and for ROOT5

```
tail /cvmfs/star.sdcc.bnl.gov/star-spack/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/root-5.34.38-eyawaunrtayjlt3aqon5claakm3c7xl7/etc/system.rootrc 
```

**Comment by plexoos** [comment]
> I expect more issues moving forward
> 
>     * a collapse of xrootd access due to alos missing directive in `rootlogon.C` .
Please send it my way.
 
>     * break of the mechanism by which a user's custom logon script would be loaded
Could you elaborate on what you expect here and remind me how ROOT picks up a user’s logon script?

>     * etc ...

**Comment by plexoos** [comment]
@genevb Here’s why you’re still seeing that error:

```
[rcas6003] ~/> starver SL24x config/v0.3.0-rhel7-root6.24.06
[rcas6003] ~/> which root4star
/afs/rhic.bnl.gov/star/packages/SL24x/.sl73_gcc485/bin/root4star
[rcas6003] ~/> root4star -b -l
root4star: error while loading shared libraries: libCore.so.6.24: cannot open shared object file: No such file or directory
```

The `starver SL24x config/v0.3.0-rhel7-root6.24.06` command doesn't switch to ROOT6 when GROUP_DIR is set to either `/afs/...` or `/star/nfs4/...` You can confirm this with:

```
[rcas6005] ~/> setup nfs4
[rcas6005] ~/> setup 64b
[rcas6005] ~/> starver SL24x config/v0.3.0-rhel7-root6.24.06
[rcas6005] ~/> root4star -l -b
root4star: error while loading shared libraries: libCore.so.6.24: cannot open shared object file: No such file or directory
[rcas6005] ~/> which root
/cvmfs/star.sdcc.bnl.gov/star-spack/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/root-5.34.38-eyawaunrtayjlt3aqon5claakm3c7xl7/bin/root
[rcas6005] ~/> echo $ROOTSYS
/cvmfs/star.sdcc.bnl.gov/star-spack/spack/opt/spack/linux-rhel7-x86_64/gcc-4.8.5/root-5.34.38-eyawaunrtayjlt3aqon5claakm3c7xl7
```

This cannot be fixed by modifying anything in rootlogon.C. The problem is in `starver`, and Jerome needs to update it with changes from his private directory.

Here's the relevant diff:

```diff
[rcas6005] ~/> diff /afs/rhic.bnl.gov/rhstar/group/.starver /star/u/jeromel/work/STAR/group/.starver
25,38d24
< 
< if ( -e $GROUP_DIR/group_env.csh && ! $?EXEFLOGIN ) then
<         source $GROUP_DIR/group_env.csh
< 	if ( $?prompt ) then
< 	    if ( ! -e $STAR) then
< 		echo "$STAR_LEVEL is incompletely defined."
< 		echo "Could not find $STAR"
< 	    endif
< 	endif
< 	#echo "$STAR"
< 	#echo "$STAR_LEVEL"	#echo "$LD_LIBRARY_PATH"
< endif
< 
< 
78a65,67
> if ( $?DECHO ) then
>     echo "$0 :: Aftre checking the config, setting STAR_CF to [$cf]"
> endif
109c98,108
< 
---
> # Should be done at the end because we make a lot of checks
> # for the config that may be passed around in recursive manner
> if ( -e $GROUP_DIR/group_env.csh && ! $?EXEFLOGIN ) then
>         source $GROUP_DIR/group_env.csh
> 	if ( $?prompt ) then
> 	    if ( ! -e $STAR) then
> 		echo "$STAR_LEVEL is incompletely defined."
> 		echo "Could not find $STAR"
> 	    endif
> 	endif
> endif
```

**Comment by genevb** [comment]
Here are my findings....

1. I do replicate the @plexoos finding of getting the CVMFS ROOT5 instead of ROOT6 when following these specific instructions:
```
setup nfs4
setup 64b
starver SL24x config/v0.3.0-rhel7-root6.24.06
echo $ROOTSYS
```

2. If I make my own GROUP_DIR as a copy of the general one on AFS, but I copy over .starver from Jerome's GROUP_DIR as proposed by @plexoos , and then I use my own GROUP_DIR (either in my login/cshrc, or using `setenv` at the prompt before the above commands), I do get the correct version of ROOT (ROOT6), but I am then back to the large number of CLING errors at run-time: for both plain ROOT (root) and root4star:
```
> root4star -b -l
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for StarMC.h
   requested to autoload type StarMC
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for TGiant3.h
   requested to autoload type Gcflag_t
...
```

3. If I do as in point 2 above, but also copy over rootenv.csh from Jerome's GROUP_DIR (in which he modifies the include path as he noted), I get no CLING errors.

So I think the point stands that the include paths needs to be properly modified somewhere.

I looked at the value of $ROOT_INCLUDE_PATH with and without Jerome's rootenv.csh. Without, I get CVMFS locations for:
```
star-env-0.3.0
star-table-0.1.1
kitrack-01-10-star-1
genfit-02-00-00
```
With Jerome's patch, it adds include paths for:
```
/star/nfs4/AFS/star/packages/SL23f/.sl73_x8664_gcc485/include
/star/nfs4/AFS/star/packages/SL24x/.sl73_x8664_gcc485/include
```
I assume the SL23f is added because $STAR is starpro by default, which is currently SL23f.

I also looked at the output of `.include` when running `root4star -b -l` in both cases. The first few items are the above 4 (or 6) include paths, and then a large number of other paths that are the same in both cases, and then near the end, the one without Jerome's rootenv.csh has:
```
/star/nfs4/AFS/star/packages/SL24x/.sl73_x8664_gcc485/include
```
So both cases have this SL24x include path (this matches what @klendathu2k reported earlier in this issue when he looked at the CLING errors), but one has it nearer the beginning and the other has it nearer the end of the list; and also one has SL23f's path (though the CLING errors refer to includes that are in both SL23f and SL24x, so I don't think the SL23f difference is critical). My impression is that rootlogon.C is doing what it is supposed to do to make sure `.include` gives the needed paths, but this is not sufficient (is too late?) at the moment in time that one executes root4star or plain ROOT.

(sidenote: at this moment, I don't know how plain ROOT knows to use .rootrc from $STAR, but the behavior of plain ROOT and root4star appear to be identical here)

_________

So, I tried the following modification of rootlogon.C:  Move  the 6 `gInterpreter->AddIncludePath();` lines from the end to the beginning.

Result: plain ROOT no longer shows any CLING errors, while root4star now shows only 3 CLING errors (StarMc, Gcflag_t, and TGiant3, as @klendathu2k reported earlier). The implication seems to be that the paths for those 3 needs to be known before rootlogon.C is read in (and I can't say I know what the appropriate way is to resolve that, though Jerome's rootenv.csh patch does resolve it), while the rest can be solved by re-ordering rootlogon.C.

Comments/insights are welcome.

**Comment by fgeurts** [comment]
At the S&C meeting on Sept.10, it was mentioned that this issue has meanwhile been resolved.
